package com.swapnadeep.week1.ad_lab_servlet;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.annotation.WebServlet;

import java.io.IOException;

@WebServlet("/hello")
public class HelloServlet extends HttpServlet {

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        response.setContentType("text/html");

        // Getting request parameters
        String name = request.getParameter("name");

        // Creating a new thread for processing the request
        Thread processingThread = new Thread(() -> {
            try {
                // Simulating a delay for processing
                Thread.sleep(5000);

                // Sending response back to the client
                PrintWriter out = response.getWriter();
                out.println("<html><body>");
                out.println("<h1>Hello, " + name + "!</h1>");
                out.println("<p>This response is generated by a multi-threaded servlet.</p>");
                out.println("</body></html>");
            } catch (InterruptedException | IOException e) {
                e.printStackTrace();
            }
        });

        processingThread.start();
    }

    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        // Handling POST requests
        // You can implement POST request processing here
        doGet(request, response);
    }
}
